// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zysfnkbwyhrfnpvcnptp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5c2Zua2J3eWhyZm5wdmNucHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4Mjc2MTYsImV4cCI6MjA2NDQwMzYxNn0.BpnfLcLqZ9J3FP8qZ6m968i5LJkgVRl5lm2ml_VQBag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);